/**
 * Word-level Kannada safety dictionary.
 * ─────────────────────────────────────
 * Used as the LAST step inside `kn()` to convert any leftover individual
 * English words inside otherwise-translated text. This guarantees that
 * dataset-driven sentences (eligibility/explanation text) never appear
 * as raw English in Kannada mode, even when no phrase regex matches.
 *
 * Keys MUST be lowercase. Lookup is case-insensitive but preserves the
 * surrounding punctuation/whitespace of the original sentence.
 */

export const WORD_KN: Record<string, string> = {
  // articles / connectors
  a: "ಒಂದು",
  an: "ಒಂದು",
  the: "",
  and: "ಮತ್ತು",
  or: "ಅಥವಾ",
  of: "ನ",
  for: "ಗಾಗಿ",
  to: "ಗೆ",
  with: "ಜೊತೆ",
  from: "ಯಿಂದ",
  by: "ಮೂಲಕ",
  in: "ನಲ್ಲಿ",
  on: "ಮೇಲೆ",
  at: "ನಲ್ಲಿ",
  is: "ಆಗಿದೆ",
  are: "ಆಗಿವೆ",
  be: "ಆಗಿರಬೇಕು",
  must: "ಬೇಕು",
  may: "ಆಗಬಹುದು",
  can: "ಸಾಧ್ಯ",
  not: "ಅಲ್ಲ",
  if: "ಆದರೆ",
  then: "ನಂತರ",
  also: "ಸಹ",
  only: "ಮಾತ್ರ",
  all: "ಎಲ್ಲ",
  any: "ಯಾವುದೇ",
  no: "ಇಲ್ಲ",
  yes: "ಹೌದು",
  per: "ಪ್ರತಿ",
  up: "ವರೆಗೆ",
  under: "ಕೆಳಗೆ",
  above: "ಮೇಲೆ",
  below: "ಕೆಳಗೆ",
  more: "ಹೆಚ್ಚು",
  less: "ಕಡಿಮೆ",
  than: "ಕ್ಕಿಂತ",

  // recommendation / scoring vocab
  scheme: "ಯೋಜನೆ",
  schemes: "ಯೋಜನೆಗಳು",
  yojana: "ಯೋಜನೆ",
  recommended: "ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ",
  recommendation: "ಶಿಫಾರಸು",
  recommendations: "ಶಿಫಾರಸುಗಳು",
  match: "ಹೊಂದಿಕೆ",
  matched: "ಹೊಂದಿಕೆಯಾಗಿದೆ",
  matches: "ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ",
  matching: "ಹೊಂದಿಕೆ",
  alignment: "ಹೊಂದಾಣಿಕೆ",
  aligns: "ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ",
  strong: "ಬಲವಾದ",
  strongly: "ಬಲವಾಗಿ",
  partial: "ಭಾಗಶಃ",
  partially: "ಭಾಗಶಃ",
  highly: "ಅತ್ಯಂತ",
  limited: "ಸೀಮಿತ",
  profile: "ಪ್ರೊಫೈಲ್",
  eligibility: "ಅರ್ಹತೆ",
  eligible: "ಅರ್ಹ",
  ineligible: "ಅರ್ಹರಲ್ಲ",
  criteria: "ಮಾನದಂಡ",
  criterion: "ಮಾನದಂಡ",
  missing: "ಕೊರತೆಯಿರುವ",
  available: "ಲಭ್ಯ",
  applicable: "ಅನ್ವಯಿಸುತ್ತದೆ",
  applicants: "ಅರ್ಜಿದಾರರು",
  applicant: "ಅರ್ಜಿದಾರ",
  apply: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
  applies: "ಅನ್ವಯಿಸುತ್ತದೆ",
  exceptions: "ವಿನಾಯಿತಿಗಳು",
  exception: "ವಿನಾಯಿತಿ",
  consider: "ಪರಿಗಣಿಸಿ",
  update: "ನವೀಕರಿಸಿ",
  updating: "ನವೀಕರಿಸುವುದು",
  changes: "ಬದಲಾವಣೆಗಳು",
  change: "ಬದಲಾವಣೆ",
  circumstances: "ಪರಿಸ್ಥಿತಿ",
  current: "ಪ್ರಸ್ತುತ",
  become: "ಆಗಬಹುದು",
  information: "ಮಾಹಿತಿ",
  details: "ವಿವರಗಳು",
  status: "ಸ್ಥಿತಿ",
  reason: "ಕಾರಣ",
  reasons: "ಕಾರಣಗಳು",
  because: "ಏಕೆಂದರೆ",
  however: "ಆದರೆ",
  therefore: "ಆದ್ದರಿಂದ",

  // demographic vocab
  age: "ವಯಸ್ಸು",
  income: "ಆದಾಯ",
  location: "ಸ್ಥಳ",
  state: "ರಾಜ್ಯ",
  district: "ಜಿಲ್ಲೆ",
  gender: "ಲಿಂಗ",
  male: "ಪುರುಷ",
  female: "ಮಹಿಳೆ",
  category: "ವರ್ಗ",
  occupation: "ಉದ್ಯೋಗ",
  education: "ಶಿಕ್ಷಣ",
  qualification: "ಅರ್ಹತೆ",
  social: "ಸಾಮಾಜಿಕ",
  demographic: "ಜನಸಂಖ್ಯಾ",
  geographic: "ಭೌಗೋಳಿಕ",
  family: "ಕುಟುಂಬ",
  household: "ಕುಟುಂಬ",
  households: "ಕುಟುಂಬಗಳು",
  citizen: "ನಾಗರಿಕ",
  citizens: "ನಾಗರಿಕರು",
  resident: "ನಿವಾಸಿ",
  residents: "ನಿವಾಸಿಗಳು",
  student: "ವಿದ್ಯಾರ್ಥಿ",
  students: "ವಿದ್ಯಾರ್ಥಿಗಳು",
  farmer: "ರೈತ",
  farmers: "ರೈತರು",
  women: "ಮಹಿಳೆಯರು",
  woman: "ಮಹಿಳೆ",
  youth: "ಯುವಕರು",
  unemployed: "ನಿರುದ್ಯೋಗಿ",
  general: "ಸಾಮಾನ್ಯ",
  rural: "ಗ್ರಾಮೀಣ",
  urban: "ನಗರ",
  india: "ಭಾರತ",
  indian: "ಭಾರತೀಯ",

  // benefits / financial vocab
  loan: "ಸಾಲ",
  loans: "ಸಾಲಗಳು",
  credit: "ಸಾಲ",
  interest: "ಬಡ್ಡಿ",
  collateral: "ಖಾತರಿ",
  subsidy: "ಸಬ್ಸಿಡಿ",
  subsidies: "ಸಬ್ಸಿಡಿಗಳು",
  scholarship: "ವಿದ್ಯಾರ್ಥಿವೇತನ",
  scholarships: "ವಿದ್ಯಾರ್ಥಿವೇತನಗಳು",
  pension: "ಪಿಂಚಣಿ",
  insurance: "ವಿಮೆ",
  health: "ಆರೋಗ್ಯ",
  healthcare: "ಆರೋಗ್ಯ",
  housing: "ವಸತಿ",
  agriculture: "ಕೃಷಿ",
  employment: "ಉದ್ಯೋಗ",
  entrepreneurship: "ಉದ್ಯಮಿತ್ವ",
  business: "ವ್ಯಾಪಾರ",
  enterprise: "ಉದ್ಯಮ",
  enterprises: "ಉದ್ಯಮಗಳು",
  small: "ಸಣ್ಣ",
  medium: "ಮಧ್ಯಮ",
  micro: "ಸೂಕ್ಷ್ಮ",
  benefit: "ಸೌಲಭ್ಯ",
  benefits: "ಸೌಲಭ್ಯಗಳು",
  financial: "ಆರ್ಥಿಕ",
  assistance: "ಸಹಾಯ",
  support: "ಬೆಂಬಲ",
  training: "ತರಬೇತಿ",
  skill: "ಕೌಶಲ್ಯ",
  development: "ಅಭಿವೃದ್ಧಿ",
  welfare: "ಕಲ್ಯಾಣ",
  government: "ಸರ್ಕಾರಿ",
  scheme_label: "ಯೋಜನೆ",

  // time / amounts
  year: "ವರ್ಷ",
  years: "ವರ್ಷಗಳು",
  month: "ತಿಂಗಳು",
  months: "ತಿಂಗಳುಗಳು",
  annum: "ವರ್ಷ",
  annual: "ವಾರ್ಷಿಕ",
  monthly: "ಮಾಸಿಕ",
  daily: "ದೈನಂದಿನ",
  ongoing: "ನಡೆಯುತ್ತಿದೆ",
  closed: "ಮುಚ್ಚಿದೆ",
  open: "ತೆರೆದಿದೆ",
  deadline: "ಗಡುವು",
  lakh: "ಲಕ್ಷ",
  lakhs: "ಲಕ್ಷ",
  crore: "ಕೋಟಿ",
  crores: "ಕೋಟಿ",
  rupees: "ರೂಪಾಯಿ",
  rupee: "ರೂಪಾಯಿ",
};
